#!/bin/sh

set -e

if dpkg-divert --list | grep -F "wl1251-nvs.bin"
then
        dpkg-divert --remove --package wl1251-cal \
        --no-rename /lib/firmware/ti-connectivity/wl1251-nvs.bin
fi

udevadm control --reload-rules && udevadm trigger
